'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DBUSB_Maker.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to color black/light-gray white/black light-gray/black light-gray/black
        '''timeout 30
        '''default 2
        '''
        '''title BOOT FROM HARD DISK
        '''root
        '''
        '''title
        '''root
        '''
        '''title     &gt;&gt; Boot Windows (AUTO)\n
        '''find --set-root --ignore-floppies --ignore-cd /bootmgr || find --set-root --ignore-floppies --ignore-cd /ntldr || rootnoverify (hd0) &amp;&amp; chainloader +1 &amp;&amp; boot
        '''map () (hd0) &amp;&amp; map (hd0) () &amp;&amp; map --rehook
        '''find --set-root --devices=h /bootmgr || find --set-root --ignore-floppies --ignore-cd /ntldr
        '''chainloader /bootmgr || chainlo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BootLST() As String
            Get
                Return ResourceManager.GetString("BootLST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property fbinstExe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("fbinstExe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gif_Loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gif_Loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property grldr() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("grldr", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property HDAT2_IMA() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("HDAT2_IMA", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to default 2
        '''color black/light-gray white/black light-gray/black light-gray/black
        '''title HDD TESTING TOOLS:
        '''root
        '''
        '''title STORAGE TESTING TOOLS
        '''root
        '''
        '''title
        '''root
        '''
        '''title     &gt;&gt; HDAT2 v4.9 BETA 1\n\n The main functions of this program are to test and repair (regenerate) bad\n sectors for detected devices. Supports ATA/ATAPI/SATA/SCSI/USB devices.
        '''find --set-root --ignore-floppies --ignore-cd /DBUSB/IMAGES/HDDTOOLS/HDAT2.IMA.gz
        '''map --mem /DBUSB/IMAGES/HDDTOOLS/HDAT2.IMA.gz (fd0)
        '''map --hook
        '''chainloader  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HddtoolsLST() As String
            Get
                Return ResourceManager.GetString("HddtoolsLST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Ico_DBUSB() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_DBUSB", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ico_Exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_Exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ico_Format() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_Format", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ico_HDD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_HDD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ico_HDD1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_HDD1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ico_Help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_Help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ico_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ico_Manual() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_Manual", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ico_Notepad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_Notepad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ico_NotFound() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_NotFound", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ico_Refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_Refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ico_Test() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_Test", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ico_USB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_USB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ico_USB1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_USB1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ico_VM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_VM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Memtest86_5_01() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Memtest86_5_01", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Memtest86_6_2_0() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Memtest86_6_2_0", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to timeout 30
        '''default 3
        '''color black/light-gray white/black light-gray/black light-gray/black
        '''
        '''title MEMORY TESTING TOOLS:
        '''root
        '''
        '''title
        '''root
        '''
        '''title     &gt;&gt; MemTest86+  (v.5.01)\n\n MemTest86+ v5.01 is designed to test and stress-test RAM. It verifies that the\n RAM will accept and retain arbitrary patterns of data and that there are no\n errors and no conflicts between memory addresses.
        '''find --set-root --ignore-floppies --ignore-cd /DBUSB/IMAGES/MEMTOOLS/Memtest86+5.01.ISO
        '''map --mem /DBUSB/IMAGES/MEMT [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MemtoolsLST() As String
            Get
                Return ResourceManager.GetString("MemtoolsLST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to color black/light-gray white/black light-gray/black light-gray/black
        '''timeout 30
        '''default 14
        '''
        '''title DBUSB - Main Menu
        '''root
        '''
        '''title
        '''root
        '''
        '''title     &gt;&gt; Memory Testing Tools
        '''configfile /DBUSB/IMAGES/MEMTOOLS/Memtools.LST
        '''
        '''title     &gt;&gt; Storage Testing Tools
        '''configfile /DBUSB/IMAGES/HDDTOOLS/Hddtools.LST
        '''
        '''title
        '''root
        '''
        '''title
        '''root
        '''
        '''title
        '''root
        '''
        '''title
        '''root
        '''
        '''title
        '''root
        '''
        '''title
        '''root
        '''
        '''title
        '''root
        '''
        '''title
        '''root
        '''
        '''title
        '''root
        '''
        '''title     Power Options
        '''root
        '''
        '''title     &gt;&gt; Boot Manager ... [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MenuLST() As String
            Get
                Return ResourceManager.GetString("MenuLST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property qemuBiosBin() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("qemuBiosBin", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property qemuQemuExe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("qemuQemuExe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property qemuVgabiosBin() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("qemuVgabiosBin", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
